[versions]
kotlin = "2.0.0"
agp = "8.13.2"

[libraries]
androidx-core = "androidx.core:core-ktx:1.13.1"
appcompat = "androidx.appcompat:appcompat:1.6.1"
material = "com.google.android.material:material:1.11.0"

compose-ui = "androidx.compose.ui:ui:1.6.0"
compose-material3 = "androidx.compose.material3:material3:1.2.0"
navigation-compose = "androidx.navigation:navigation-compose:2.7.7"
compose-icons = "androidx.compose.material:material-icons-extended:1.6.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }